### ISSUE TITLE
读取excel问题

### ISSUE THREAD

**Issue by rymm1** [Crab2died/Excel4J#19]
如果有合并行的单元格 好像读取有问题 会多一条记录
public <T> List<T> readExcel2Objects(InputStream is, Class<T> clazz)

**Comment by rymm1** [comment]
读取日期列也有问题啊

**Comment by Crab2died** [comment]
日期格式太多，你可以用 com.github.converter.ReadConvertible 转换器转换

**Comment by rymm1** [comment]
有合并行的 读取titleMap问题 看了吗

**Comment by JackWuChengHao** [comment]
使用的是
<artifactId>Excel4J</artifactId>
<version>2.1.4-Final2</version>
关于程序上的一点问题，在读取excel文件时Utils 类中getCellValue调用了Cell的getCellTypeEnum方法，但是报错
java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.getCellTypeEnum()Lorg/apache/poi/ss/usermodel/CellType;
因为依赖的为poi 3.17了
getCellTypeEnum
POI 3.15 beta 3 Will be renamed to getCellType() when we make the CellType enum transition in POI 4.0. See bug 59791.
所以我想请问作者是怎么没有报错问题的，谢谢。

**Comment by Crab2died** [comment]
@JackWuChengHao 你这个应该是引用了低版本的 POI jar包，建议升级至3.17版本
