### ISSUE TITLE
基于模板Map<String, Collection<Object.toString>>导出问题

### ISSUE THREAD

**Issue by sfx478076717** [Crab2died/Excel4J#29]
public void exportObject2Excel(String templatePath, int sheetIndex, Map<String, List<?>> data, Map<String, String> extendMap, Class clazz, boolean isWriteHeader, OutputStream os)方法，
为什么data的定义必须是Map<String,List<?>>，这里的问号❓为什么非要加上？
不加就报错，报can not reslove method ，我专门指定类型也会报错。求作者解释一下。

**Comment by Crab2died** [comment]
hello,这个是基于模板导出的一种，你先必须在模板里&+key的形式定义好模板，然后这个key对应导出data的map的key，这样导出的数据才会是你模板的样式，具体细节请看这个例子https://github.com/Crab2died/Excel4J#4-%E5%9F%BA%E4%BA%8E%E6%A8%A1%E6%9D%BFmapstring-collectionobjecttostring%E5%AF%BC%E5%87%BA
