### ISSUE TITLE
复杂关系 怎么查询 替换 输出

### ISSUE THREAD

**Issue by HaimmingYu** [Crab2died/Excel4J#6]
复杂关系 怎么查询 替换 输出

**Comment by TonyYule** [comment]
` @ExcelField(title = "负责人", order = 26)
    private SysUser principal;//负责人`
嵌套对象 可不可以用反射方式 在注解里面添加 字段 获取对象里面的字段

**Comment by TonyYule** [comment]
[https://github.com/thinkgem/jeesite/tree/master/src/main/java/com/thinkgem/jeesite/common/utils/excel](https://github.com/thinkgem/jeesite/tree/master/src/main/java/com/thinkgem/jeesite/common/utils/excel)可以参考这个

**Comment by yiqihaha** [comment]
这个你可以使用 WriteConvertible
