### ISSUE TITLE
引入就报错。。好像和demo演示的不一样

### ISSUE THREAD

**Issue by qq727127158** [Crab2died/Excel4J#8]
不能支持模板导出
![image](https://user-images.githubusercontent.com/22268134/32321892-a8ba1300-bf90-11e7-8fd3-ec0b53e7f4c4.png)

**Comment by Crab2died** [comment]
检查参数类型或个数是否正确

**Comment by qq727127158** [comment]
@Crab2died  谢谢，我后来可以导出了，但是模板导出有个问题。设置模板中的标题时，会把原本标题的首行覆盖掉并且开始行也不是第一行，所以采用了另一个开源工具类。
